### ISSUE TITLE
How can I achieve dynamic stretches for PVDR

### ISSUE THREAD

**Issue by lszhou0126** [ltfat/phaseret#12]
Hi,
As the executable pvdoneright.exe provide a bar to change the stretches. However, the stretches in demo_phasevocoder.m is fixed. How can I achieve dynamic stretches over time, and how to deal with the hop change between frames.

**Comment by nholighaus** [comment]
Hi, 
I only have a partial, not very satisfactory answer to this at the moment, maybe someone else can add to it. The demo in PhaseReT is only supposed to be a basic demonstration and not written with dynamic stretching in mind and adding this functionality is currently not a priority. That said dynamic stretching would be implemented as in any other phase vocoder implementation that allows doing so, i.e., the different stretches are applied block-wise, likely in conjunction with some compensation to account for changing hop size / synthesis windows. 

If susnak sees this, he might be able to point you at the right literature to look at.

**Comment by susnak** [comment]
Hi,
I am afraid I don't have any literature to point you to. The current Matlab demo can't be easily adapted to dynamic changes.
Zdenek

**Comment by nholighaus** [comment]
That is true, but I did interpret this as a more general question about how dynamic changes would be achieved with PVDR-style usage of RTPGHI. 

As there are currently no plans to offer this functionality directly in PhaseReT, I'm closing this issue.
