### ISSUE TITLE
errors when run libphaseret tests

### ISSUE THREAD

**Issue by Beronx86** [ltfat/phaseret#2]
Hi @susnak, I try running the phaseret-0.2.0/libphaseret/testing/mUnit test codes, but I encounter some errors. First, the `loadlibphaseret.m` cannot load the lib correctly. Then I run `make shared` in `libltft` and `libphaseret`, and modify the `loadlibphaseret.m` script to 
```
function loadlibphaseret(varargin)

definput.keyvals.lib='libphaseret.so';
definput.flags.phase={'load','reload'};
[flags,~,lib]=ltfatarghelper({'lib'},definput,varargin);

[~,libname]=fileparts(lib);
    
if libisloaded(libname) 
    if flags.do_reload
        unloadlibrary(libname);
    else
        error('%s: libphaseret is already loaded. Use ''reload'' to force reload.',upper(mfilename));
    end
end

warning('off');
currdir = fileparts(mfilename('fullpath'));
libpath = [currdir, filesep, '..', filesep, '..' , filesep,'build',filesep,lib];
headerpath = [currdir, filesep, '..', filesep, '..' , filesep, 'include',filesep,'phaseret.h'];
loadlibrary(libpath,headerpath,'mfilename','libphaseretprotofile.m', 'includepath', '/home/liupeng/phaseret-0.2.0/libphaseret/include', 'includepath', '/home/liupeng/phaseret-0.2.0/libltfat/include');
warning('on');
```
This script can run without any error.
But when I run `test_libphaseret_gla.m`, it says
```
Error using calllib
Method was not found.

Error in test_libphaseret_gla (line 20)
calllib('libphaseret','phaseret_gla_d',cinPtr,g,L,gl,1,a,M,maxit,coutPtr);
```
Could you please offer some help?

**Comment by susnak** [comment]
Hi,
I am off this week. I will try to get to you next week.
From what I can immediately see, you should run _make munit_ in both libltfat and libphaseret instead of _make shared_. It will generate the missing headers compatible with loadlibrary.
Zdenek

**Comment by Beronx86** [comment]
Hi @susnak , `make munit` solve the problem. Thanks a lot!

**Comment by susnak** [comment]
Great! Then I close this issue.

**Comment by OswaldoBornemann** [comment]
@Beronx86 may i ask how to generate `libphaseret.so` file ?
