### ISSUE TITLE
How can I use your code to reconstruct a signal with Griffin & Lim algorithm?

### ISSUE THREAD

**Issue by littleTwelve** [ltfat/phaseret#4]
Now I have some images (.jpg) which are all spectrogram generated by the matlab function'spectrogram'. How can I use your code to reconstruct signals corresponding to the spectrogram  with Griffin & Lim algorithm?

**Comment by susnak** [comment]
Hi,
not sure how spectrogram from Matlab works so first of, convert your image to a matrix such that row indicies are frequencies and column indices are time positions. I.e. if you used NFFT=1024  , the matrix dimensions will be (NFFT/2+1) x hops.
Also check if you really have the magnitude of the coefficients and not log of it.
Then you run:
```
c = gla(s,g,a,M)
f = idgtreal(c,{'dual',g},a,M,'timeinv')
```
where _s_ is your magnitude matrix, _g_ is probably 'hamming', _a_ is window length - overlap, M is NFFT.
Hope it helps.
Zdenek

**Comment by OswaldoBornemann** [comment]
@susnak could you show more example ?

**Comment by susnak** [comment]
You can try to follow the example at
http://ltfat.github.io/phaseret/doc/gabor/

**Comment by OswaldoBornemann** [comment]
@susnak thanks a lot.!
