### ISSUE TITLE
More Python example

### ISSUE THREAD

**Issue by OswaldoBornemann** [ltfat/phaseret#7]
Noticed in `test_libltfat_fftshift.py`,  @susnak you show us how to use `ltfat` with `python`. Could you show some example about how to use `phaseret` with `python` ?

**Comment by susnak** [comment]
Hi, I have never got around to make a proper python wrapper. I did write some more tests, but the code is ugly and I have never made it public. In this archive 
[python_libphaseret_example.zip](https://github.com/ltfat/phaseret/files/3339023/python_libphaseret_example.zip) have a look at test_gla.py
Should run as it is. You might have to install some python packages.
Good luck!
Zdenek

**Comment by OswaldoBornemann** [comment]
@susnak  love you susnak.!!

**Comment by tsungruihon** [comment]
@susnak when i run the follow code, it just show error `TypeError: 'int(*)(phaseret_gla_plan_s *, int *, int)' expects 3 arguments, got 2`

`status = getattr(libphaseret, 'phaseret_gla_execute_s')(gplan[0], 10)`

Could you give me a hint ? Thanks.

**Comment by tsungruihon** [comment]
@susnak  i was trying to use `phaseret_gla_s` like below

```
status = getattr(libphaseret, 'phaseret_gla_s')(
    ffi.cast("float (*)[2]", cout.ctypes.data),
    ffi.cast("int *", 0),
    ffi.cast("float *",g.ctypes.data),
    L, gl, 1, a, M, 10, 
    ffi.cast("float (*)[2]",fout.ctypes.data)
)
```

but when i plot the `fout`, the signal seems awkward. I am sure something i was wrong.

<img width="464" alt="Screen Shot 2019-06-30 at 12 25 18 AM" src="https://user-images.githubusercontent.com/11624203/60386868-92993c80-9acd-11e9-92bc-0f7aff21e38b.png">
