### ISSUE TITLE
Error using phaseretmex on linux(ubuntu 16) on MATLAB

### ISSUE THREAD

**Issue by ghost** [ltfat/phaseret#8]
`>> phaseretmex

********* Compiling libltfat **********

********* Compiling libphaseret **********

********* Compiling MEX files **********

Error using phaseretmex (line 176)

Make failed with: 

 Error using phaseretmex (line 126)

The mex executable in not in the PATH`

All steps mentioned in the installation procedure has been followed.

**Comment by susnak** [comment]
Hi. The script calls the mex executable explicitly i.e. like you would from a terminal.
This means calling system('which mex') from the matlab prompt should return a path from the Matlab installation folder.
If I remember it correctly, the Matlab installer asks you whether to put the bin directory in the PATH.
If you haven't done so, it should be fairly straightforward to do it manually later.

**Comment by ghost** [comment]
Not sure why, but the compilation of the mex files don't seem to be necessary for the phaseret toolbox to work. I'm able to use functions like PGHI although phaseretmex throws an error when I run it. So I'm going to go ahead and close this issue. Thanks
