### ISSUE TITLE
libphaseret has not been part of the master branch since it was temporarily removed on July 30, 2018

### ISSUE THREAD

**Issue by nholighaus** [ltfat/phaseret#9]
Pretty much what is in the title. I only saw this because a colleague trying to use the current version had trouble compiling. Was there a plan for an overhaul similar to libltfat, or should the old version still work properly?

**Comment by susnak** [comment]
libphaseret is here master/libltfat/modules/libphaseret

**Comment by nholighaus** [comment]
Ok. I just downloaded a separate version of the master branch and can compile fine. So it must be a path issue for that colleague. Maybe some old version in the path. He got an error running 'phaseretmex' looking for files in the subfolder 'libphaseret/' in the phaseret base folder, which does not exist anymore. I'm closing this.
